[tool.poetry]
name = "notion2medium"
version = "0.1.0"
description = ""
authors = ["echo724 <eunchan1001@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
notion2md = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
